services:
  solcation:
    image: ghcr.io/sh-min-value/solcation-be:dev-latest
    container_name: solcation
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
