spring:
  application:
    name: solcation_be
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 60000
      max-lifetime: 1700000
      keepalive-time: 300000
      connection-timeout: 30000
      pool-name: solcationDBPool
  main:
    banner-mode: "off"
  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 30MB
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  task:
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
        await-termination-period: 60000
    execution:
      thread-name-prefix: solcationTaskPool

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

server:
  forward-headers-strategy: framework
  shutdown: graceful

springdoc:
  swagger-ui:
    persist-authorization: true

cloud:
  s3:
    bucket:
      name: solcation
      upload:
        profile:
          group: images/group_profiles/
          travel: images/travel_profiles/
        signature: signatures/