spring:
  application:
    name: solcation_be
  jpa:
    show-sql: true
  jackson:
    time-zone: Asia/Seoul
  main:
    banner-mode: "off"
  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 30MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

server:
  forward-headers-strategy: framework
  shutdown: graceful

springdoc:
  swagger-ui:
    persist-authorization: true

cloud:
  s3:
    bucket:
      name: solcation
      upload:
        profile:
          group: images/group_profiles/
          travel: images/travel_profiles/
        signature: signatures/