name: CD (dev - docker compose, self-hosted)

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch: {}

env:
  IMAGE_TAG: dev-${{ github.sha }}
  APP_DIR: ~/apps/solcation

jobs:
  build_push_deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build JAR
        run: ./gradlew clean bootJar --stacktrace

      - name: Docker login (GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ secrets.IMAGE_NAME }}:dev-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy with Docker Compose (on self-hosted runner)
        run: |
          set -e
          mkdir -p $APP_DIR
          cp docker-compose.yml $APP_DIR/
          cd $APP_DIR

          # pull 권한 필요 시 로그인 (private이면 필수)
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin

          docker compose pull
          docker compose up -d
          docker compose ps
