name: CI (Gradle + Docker build check)

on:
  pull_request:
  push:
    branches: [ "**" ]

jobs:
  gradle-build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: "ci-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
        continue-on-error: true
        timeout-minutes: 3
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew clean test -x build --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
          if-no-files-found: error

  docker-build-check:
    runs-on: ubuntu-latest
    needs: gradle-build-test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ci:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
